### ISSUE TITLE
t/lexicon/gettext.t fails on non-Linux systems

### ISSUE THREAD

**Issue by eserte** [vti/plack-i18n#1]
See http://matrix.cpantesters.org/?dist=Plack-I18N%200.02 for a pass/fail overview. 0.03 has the same problem, but currently no results on cpantesters.

It seems that the gettext.t test relies on the directory order when reading the .po files. On linux systems, readdir() returns first ru.po, then en.po. On non-linux systems it seems to be the other way around.

**Comment by vti** [comment]
Thanks. I just uploaded new release.

**Comment by eserte** [comment]
Looks good. I just sent the first pass from a non-linux system.
